- hosts: all
  tasks:
    - name: "Update packages"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: "Install apt-transport-https"
      apt:
        name: ['apt-transport-https']
        state: latest
    - name: "Install ca-certificatess"
      apt:
        name: ['ca-certificates']
        state: latest
    - name: "Install curl"
      apt:
        name: ['curl']
        state: latest
    - name: "Install software-properties-common"
      apt:
        name: ['software-properties-common']
        state: latest
    - name: Execute a command
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
