- hosts: all
  tasks:
    - name: Build Image
      shell: docker build -t "{{ var_docker_repo }}"/"{{ var_job_name }}":"{{ var_build_number }}" .
    - name: Publish Image
      shell: 
         cmd |
              docker login -u "{{var_docker_user}}" -p $"{{var_docker_user}}"
              docker push "{{ var_docker_repo }}"/"{{ var_job_name }}":"{{ var_build_number }}"
