- hosts: [Invertori.hosts] // si es que no funciona el metodo del inventori regresar a la forma de variable 
  tasks:
  
    - name: Create DockerFile
      shell:  '''
                    cat <<EOT > Dockerfile
                    FROM nginx:latest
                    COPY index.html /usr/share/nginx/html/
                '''
    - name: Build Image
      shell:  docker build -t "{{ var_docker_repo }}"/"{{ var_job_name }}":"{{ var_build_number }}" .
    - name: Publish Image
      shell:  '''
                 docker login -u $docker_user -p $docker_pass
                 docker push ${env.DOCKER_REPO}/${JOB_BASE_NAME}:${BUILD_NUMBER}
                 '''
    - name: pullimage
      shell:  docker pull "{{ var_docker_repo }}"/"{{ var_job_name }}":"{{ var_build_number }}"
    - name: run images
      shell: docker run -d -p "{{var_container_port}}":80 "{{var_docker_repo}}"/"{{var_job_name}}":"{{var_build_number}}"  
